具体的に飛んでくる例外が何かわからなくてもキャッチできる。
しかし、例外オブジェクトの値は取得できない。

tryに続くcatch節の中でも最後に一つだけ入れられる。